#JazariFresnelSim Optimization & Thermal Parameters
#Sat Apr 11 19:44:11 TRT 2026
target_temperature_c=80.0
receiver_emissivity=0.12
min_mirrors=2
wind_speed_ms=2.5
min_mirror_spacing=15.0
max_mirror_spacing=80.0
receiver_absorptance=0.94
max_rec_diam=20.0
mirror_length_cm=200.0
min_rec_height=30.0
min_rec_diam=10.0
max_mirror_width=30.0
max_rec_height=300.0
min_mirror_width=5.0
max_mirrors=10
